INSERT INTO cursos (categoria, nome)
VALUES ("Mandarim", "Idiomas"),
       ("ORACLE NEXT EDUCATION (ONE)", "Tecnologia"),
       ("Engenharia de Software", "Tecnologia"),
       ("Programação orientada a Ojbetos", "Tecnologia"),
       ("Engeharia de Requisitos", "Tecnologia"),
       ("Inglês", "Idiomas"),
       ("Marketing Digital", "Negócios"),
       ("Administração", "Negócios"),
       ("Contabilidade", "Negócios"),
       ("Design Gráfico", "Criatividade"),
       ("Desenvolvimento Web", "Tecnologia"),
       ("Ciência de Dados", "Tecnologia"),
       ("Inteligência Artificial", "Tecnologia");

INSERT INTO usuarios (email, nome, role, senha)
VALUES ('admin@email.com', 'Administrador do Sistema', 'ADMIN',
        '$2a$10$ghZIWprsXWFr6JRnTAeAJe5p0BWldn33iz0IkAgr2KT6U8IoYc.Dm'),
       ('user@email.com', 'Usuário do Sistema', 'USER', '$2a$10$aSfg5opE6j2LOlaLNMwLW.u4rUjX4UqBKs5tarFuc6vcNK9J9LYbO'),
       ('usuario1@example.com', 'Usuário 1', 'USER', 'senha1'),
       ('usuario2@example.com', 'Usuário 2', 'USER', 'senha2'),
       ('usuario3@example.com', 'Usuário 3', 'ADMIN', 'senha3');

INSERT INTO topicos (data_criacao, mensagem, status, titulo, usuario_id, curso_id)
VALUES ('2022-05-20 09:11:55',
        'Eu aprendi essas palavras (wo chile fan) e (wo chile). Ambas são traduzias como eu comi.', 'SOLUCIONADO',
        'Qual é a diferença entre mandarim padrão e mandarim coloquial?', 2, 1),
       ('2023-09-20 20:51:44', 'Quais são os benefícios do programa ONE?', 'SOLUCIONADO', 'Como posso participar?', 5,
        2),
       ('2023-09-20 19:28:00', 'Como criar um aplicativo Android?', 'NAO_SOLUCIONADO',
        'Como criar um aplicativo Android', 3, 3),
       ('2023-09-20 19:29:00', 'Como usar o Google Analytics?', 'NAO_RESPONDIDO', 'Como usar o Google Analytics', 2, 7),
       ('2023-09-20 19:30:00', 'Como criar um site responsivo?', 'NAO_RESPONDIDO', 'Como criar um site responsivo', 1,
        10),
       ('2023-09-20 19:31:00', 'Como fazer um banco de dados?', 'NAO_RESPONDIDO', 'Como fazer um banco de dados', 3,
        12),
       ('2023-09-20 19:32:00', 'Como programar em Python?', 'NAO_RESPONDIDO', 'Como programar em Python', 2, 3),
       ('2023-09-20 19:33:00', 'Como aprender inglês?', 'SOLUCIONADO', 'Como aprender inglês', 1, 6),
       ('2023-09-20 19:34:00', 'Como fazer um plano de negócios?', 'NAO_RESPONDIDO', 'Como fazer um plano de negócios',
        3, 9),
       ('2023-09-20 19:35:00', 'Como abrir uma empresa?', 'FECHADO', 'Como abrir uma empresa', 2, 9);


INSERT INTO respostas (data_criacao, mensagem, solucao, usuario_id, topico_id)
VALUES ('2023-09-20 19:53:00',
        'A atualização do curso de Engenharia de Software inclui novos conteúdos sobre design de software e arquitetura de software. Os novos conteúdos serão lançados no dia 30 de setembro.',
        0, 2, 7),
       ('2023-09-20 19:46:00',
        'Um banco de dados é um sistema de armazenamento que organiza dados de forma estruturada. Existem muitos tipos diferentes de bancos de dados, como bancos de dados relacionais, bancos de dados NoSQL e bancos de dados orientados a objetos.',
        1, 3, 6),
       ('2023-09-20 19:47:00',
        'Python é uma linguagem de programação de alto nível que é fácil de aprender e usar. É uma boa opção para iniciantes porque é relativamente simples e possui uma grande biblioteca de módulos e bibliotecas.',
        0, 1, 7),
       ('2023-09-20 19:48:00',
        'Para aprender inglês, você precisará praticar a leitura, a escrita, a fala e a audição. Existem muitos recursos disponíveis para ajudá-lo a aprender inglês, como livros, cursos online e aplicativos.',
        1, 1, 8),
       ('2023-09-20 19:49:00',
        'Um plano de negócios é um documento que descreve o seu negócio, seus objetivos e sua estratégia para alcançá-los. É uma ferramenta importante para os empreendedores que desejam iniciar ou expandir seus negócios.',
        0, 3, 9),
       ('2023-09-20 19:50:00',
        'Para abrir uma empresa, você precisará registrar sua empresa, obter licenças e autorizações necessárias e definir um plano de negócios. Você também precisará encontrar um local para sua empresa e contratar funcionários.',
        0, 2, 9),
       ('2023-09-20 19:55:00',
        'A promoção para cursos de tecnologia inclui descontos de até 50% para cursos novos. A promoção é válida até o dia 31 de dezembro.',
        1, 5, 2),
       ('2023-09-20 19:51:00',
        'Um currículo é um documento que resume suas qualificações e experiências. Ele é usado para se candidatar a empregos. Um currículo bem escrito pode ajudá-lo a se destacar da concorrência e conseguir o emprego que deseja.',
        0, 1, 7),
       ('2023-09-20 19:52:00',
        'Para encontrar um emprego, você pode usar sites de emprego, agências de emprego ou networking. Você também pode enviar seu currículo diretamente para empresas que você deseja trabalhar.',
        0, 3, 7),
       ('2023-09-20 11:06:05', 'O mandarim é o idioma oficial da China, falado por 1,1 bilhão de pessoas globalmente. Existem duas formas principais: o formal, mandarim padrão, usado em escolas e mídia, e o informal, mandarim coloquial, variando por região.',
        1, 5, 1);

